# Generated by Django 4.1.6 on 2023-07-10 11:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_recruiters_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiters',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 10, 16, 51, 41, 833469)),
        ),
    ]
