# Generated by Django 4.1.6 on 2023-07-12 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_recruiters_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiters',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 12, 16, 18, 0, 175480)),
        ),
    ]
